name: Java Build

on: [push]

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up AdoptOpenJDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16
    - name: Build with Gradle
      run: ./gradlew dist jpackage
    - name: Upload ZIP 
      uses: actions/upload-artifact@v1
      with:
        name: fxgamezip
        path: build/distributions/game2048-mac.zip
    - name: Upload PKG
      uses: actions/upload-artifact@v1
      with:
        name: fxgameinstaller
        path: build/installers/fx2048-1.0.pkg
