name: Java Build

on: [push]

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - run: |
        download_url="https://download.java.net/java/early_access/jdk17/31/GPL/openjdk-17-ea+31_macos-x64_bin.tar.gz"
        wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
    - name: Set up OpenJDK 17-EA
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/java_package.tar.gz
        java-version: '17'
        architecture: x64
    - name: Build with Gradle
      run: ./gradlew compileJava jlink jlinkZip jpackage
    - name: Upload ZIP 
      uses: actions/upload-artifact@v1
      with:
        name: fxgamezip
        path: build/distributions/game2048-mac.zip
    - name: Upload PKG
      uses: actions/upload-artifact@v1
      with:
        name: fxgameinstaller
        path: build/jpackage/fx2048-unspecified.pkg
